name: nop
description: Isolate 通信
version: 0.2.0+3
repository: https://github.com/sersr/nop

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ">=1.7.0 <2.0.0"
  characters: ">=1.2.0 <2.0.0"
  collection: ">=1.15.0 <2.0.0"
  equatable: ">=2.0.2 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
